name: goodpractice

on: [push, pull_request]

jobs:
  goodpractice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            goodpractice
            ecpc=?ignore
            grpregOverlap=?ignore
            scoop=?ignore
            squeezy=?ignore

      - name: goodpractice
        run: |
          checks <- setdiff(goodpractice::all_checks(), c("covr", "cyclocomp"))
          checks <- checks[!grepl(pattern="rcmdcheck_", x = checks)]
          x <- goodpractice::gp(checks = checks)
          print(x)
          fails <- goodpractice::failed_checks(x)
          if(length(fails)>0){print(fails); stop("failed goodpractice tests")}
        shell: Rscript {0}